db.url=jdbc:mysql://nozomi.proxy.rlwy.net:28631/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.username=root
db.password=zRUAPhpcEhbXkKCobyxCiMBptIziMnYo
db.driver=com.mysql.cj.jdbc.Driver